/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import Controlador.ControlTablas;
import Controlador.Controles;
import Modelo.TextPrompt;
import Modelo.connectDB;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author FERNEY
 */

public class Ayuda extends javax.swing.JPanel {

    /**
     * Creates new form Administrador
     */
    private connectDB conn;
    public Ayuda() {
        initComponents();
        this.setSize(980, 650);
        Icon ico = lb.getIcon();
        ImageIcon icon = (ImageIcon) ico;
        Image image = icon.getImage().getScaledInstance(lb.getWidth(), lb.getHeight(), Image.SCALE_SMOOTH);
        lb.setIcon(new ImageIcon(image));
        
        conn=new connectDB();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_bienvenido = new javax.swing.JLabel();
        btn_Abrir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(980, 650));
        setMinimumSize(new java.awt.Dimension(980, 650));
        setLayout(null);

        lb_bienvenido.setFont(new java.awt.Font("SimSun-ExtB", 1, 36)); // NOI18N
        lb_bienvenido.setText("Manual de Usuario");
        add(lb_bienvenido);
        lb_bienvenido.setBounds(260, 10, 420, 40);

        btn_Abrir.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btn_Abrir.setText("Abrir Documento");
        btn_Abrir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, new java.awt.Color(153, 153, 153), java.awt.Color.cyan, java.awt.Color.black));
        btn_Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AbrirActionPerformed(evt);
            }
        });
        add(btn_Abrir);
        btn_Abrir.setBounds(220, 358, 280, 60);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("el documento");
        add(jLabel1);
        jLabel1.setBounds(20, 240, 850, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setText("El documento contiene información básica y recomendaciones de uso que le serán de ayuda");
        add(jLabel2);
        jLabel2.setBounds(20, 70, 850, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setText("para mejorar la navegación, la búsqueda de información, el uso de las  diferentes  utilidades");
        add(jLabel3);
        jLabel3.setBounds(20, 100, 850, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setText("y servicios que le ofrece The BArber's House");
        add(jLabel4);
        jLabel4.setBounds(20, 130, 850, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel5.setText("Consulte con el proveedor el manual de usuario o presione el botón Abrir Documento que se");
        add(jLabel5);
        jLabel5.setBounds(20, 180, 850, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel6.setText("encuentra en la parte inferior que guiará a la pagina del proveedor para  que pueda descargar ");
        add(jLabel6);
        jLabel6.setBounds(20, 210, 850, 40);

        lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/back1.png"))); // NOI18N
        add(lb);
        lb.setBounds(0, 0, 930, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AbrirActionPerformed
        // TODO add your handling code here:
        
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop enlace = Desktop.getDesktop();
                if (enlace.isSupported(Desktop.Action.BROWSE)) {
                    enlace.browse(new URI("https://drive.google.com/file/d/1kFfrcwwQPgv4gECUFDwBFYBtYkvfWjAb/view?usp=share_link"));
                }

            }

        } catch (IOException | URISyntaxException e) {
            JOptionPane.showMessageDialog(null, "No se puede abrir el archivo " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_AbrirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Abrir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb_bienvenido;
    // End of variables declaration//GEN-END:variables
}
