/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package vista;

import Controlador.Controles;
import Modelo.TextPrompt;
import Modelo.connectDB;
import java.awt.Color;
import java.awt.Image;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import panel.Empleado;

/**
 *
 * @author FERNEY
 */
public class Login extends java.awt.Frame {

    connectDB cc = new connectDB();
    Connection con = cc.getConection();
    Empleado empleado;
    Controles controles;

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(450, 245);
        TextPrompt txt1 = new TextPrompt("      Ingresa su usuario", txt_usuario);
        TextPrompt txt2 = new TextPrompt("      Ingresa su contraseña", txt_password);
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/logo.png")).getImage());
        setTitle("The Barber's House");
        Icon ico = lb_background.getIcon();
        ImageIcon icon = (ImageIcon) ico;
        Image image = icon.getImage().getScaledInstance(lb_background.getWidth(), lb_background.getHeight(), Image.SCALE_DEFAULT);
        lb_background.setIcon(new ImageIcon(image));

        empleado = new Empleado();
        controles = new Controles();
        //link
//         
         
         
    }

    public void validarAcceso() {
        int result = 0;
        try {
            String user = txt_usuario.getText();
            String pass = String.valueOf(txt_password.getText());
            if (user.equals("") && pass.equals("")) {
                JOptionPane.showMessageDialog(null, "Campos vacios\n Vuelve a intentar");
            } else {
                String sql = "SELECT * FROM barber_admin WHERE username='" + user + "' AND password='" + pass + "'";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                if (rs.next()) {
                    result = 1;
                    if (result == 1) {
                        this.dispose();
                        String s = rs.getString("role");
                        Principal principal = new Principal();
                        principal.setVisible(true);
                        principal.setLocationRelativeTo(null);
                        principal.disablePaneladmin(s);
                        System.out.println("Accediste modo" + s);
                    } else {
                        JOptionPane.showMessageDialog(null, "Error de acceso\n Vuelve a intentar");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Credenciales incorrectas. Vuelve a intentar de nuevo.");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de acceso\n Vuelve a intentar\n" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_bienvenido = new javax.swing.JLabel();
        lb_password = new javax.swing.JLabel();
        lb_user = new javax.swing.JLabel();
        btn_access = new javax.swing.JButton();
        txt_usuario = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_close = new javax.swing.JButton();
        btn_manual = new javax.swing.JButton();
        lb_background = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        lb_bienvenido.setBackground(new java.awt.Color(204, 204, 204));
        lb_bienvenido.setFont(new java.awt.Font("SimSun-ExtB", 1, 48)); // NOI18N
        lb_bienvenido.setText("Bienvenido!");
        add(lb_bienvenido);
        lb_bienvenido.setBounds(70, 10, 310, 40);

        lb_password.setBackground(new java.awt.Color(255, 255, 255));
        lb_password.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lb_password.setText("Contraseña:");
        add(lb_password);
        lb_password.setBounds(40, 110, 110, 24);

        lb_user.setBackground(new java.awt.Color(255, 255, 255));
        lb_user.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lb_user.setText("Usuario:");
        add(lb_user);
        lb_user.setBounds(40, 70, 100, 24);

        btn_access.setBackground(new java.awt.Color(204, 204, 204));
        btn_access.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btn_access.setText("Ingresar");
        btn_access.setActionCommand("btn_ingresar");
        btn_access.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, new java.awt.Color(153, 153, 153), java.awt.Color.cyan, java.awt.Color.black));
        btn_access.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_accessMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_accessMouseExited(evt);
            }
        });
        btn_access.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accessActionPerformed(evt);
            }
        });
        add(btn_access);
        btn_access.setBounds(100, 170, 100, 25);

        txt_usuario.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usuarioKeyTyped(evt);
            }
        });
        add(txt_usuario);
        txt_usuario.setBounds(160, 70, 240, 30);

        txt_password.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passwordKeyTyped(evt);
            }
        });
        add(txt_password);
        txt_password.setBounds(160, 110, 240, 30);

        btn_close.setBackground(new java.awt.Color(204, 204, 204));
        btn_close.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btn_close.setText("Salir");
        btn_close.setActionCommand("btn_salir");
        btn_close.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, new java.awt.Color(153, 153, 153), java.awt.Color.cyan, java.awt.Color.black));
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        add(btn_close);
        btn_close.setBounds(260, 170, 80, 25);

        btn_manual.setBackground(new java.awt.Color(204, 204, 204));
        btn_manual.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btn_manual.setText(" Ver manual de usuario");
        btn_manual.setActionCommand("btn_ingresar");
        btn_manual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, new java.awt.Color(153, 153, 153), java.awt.Color.cyan, java.awt.Color.black));
        btn_manual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_manualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_manualMouseExited(evt);
            }
        });
        btn_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manualActionPerformed(evt);
            }
        });
        add(btn_manual);
        btn_manual.setBounds(100, 210, 240, 25);

        lb_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/back3.PNG"))); // NOI18N
        add(lb_background);
        lb_background.setBounds(0, 0, 450, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */

    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btn_accessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accessActionPerformed
        // TODO add your handling code here:
        validarAcceso();

    }//GEN-LAST:event_btn_accessActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_accessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_accessMouseEntered
        // TODO add your handling code here:
        btn_access.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn_accessMouseEntered

    private void btn_accessMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_accessMouseExited
        // TODO add your handling code here:
        btn_access.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btn_accessMouseExited

    private void btn_manualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manualMouseEntered
        // TODO add your handling code here:
        btn_access.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn_manualMouseEntered

    private void btn_manualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manualMouseExited
        // TODO add your handling code here:
        btn_access.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btn_manualMouseExited

    private void btn_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manualActionPerformed
        // TODO add your handling code here:
        cc.openManual();
    }//GEN-LAST:event_btn_manualActionPerformed

    private void txt_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuarioKeyTyped
        // TODO add your handling code here:
        controles.limitedField(txt_usuario, 50, evt);
    }//GEN-LAST:event_txt_usuarioKeyTyped

    private void txt_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyTyped
        // TODO add your handling code here:
        controles.limitedField(txt_password, 32, evt);
    }//GEN-LAST:event_txt_passwordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_access;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_manual;
    private javax.swing.JLabel lb_background;
    private javax.swing.JLabel lb_bienvenido;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_user;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
