/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import panel.Administrador;
import panel.Ayuda;
import panel.Cliente;
import panel.Empleado;

/**
 *
 * @author FERNEY
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private JPanel contentPanel;
    private Administrador administrador;
    private Empleado empleado;
    private Cliente cliente;
    private Ayuda ayuda;

    public Principal() {
        initComponents();
        contentPanel = new JPanel();
        administrador = new Administrador();
        empleado = new Empleado();
        cliente = new Cliente();
        ayuda = new Ayuda();
        
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/logo.png")).getImage());
        setTitle("Login - The Barber's House");
        this.setSize(980, 650);
        contentPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
        contentPanel.setLayout(new BorderLayout(0, 0));
        setContentPane(contentPanel);
        setLocationRelativeTo(null);

        Icon ico = lb_background.getIcon();
        ImageIcon icon = (ImageIcon) ico;
        Image image = icon.getImage().getScaledInstance(lb_background.getWidth(), lb_background.getHeight(), Image.SCALE_DEFAULT);
        lb_background.setIcon(new ImageIcon(image));
    }

    public void disablePaneladmin(String admin) {
        if (admin.equals("Empleado")) {
            MenuItemAdmin.setVisible(false);
            menuItemEmpleado.setVisible(false);
        }
    }

    public void newPanel(JPanel panel) {
        contentPanel.removeAll();
        contentPanel.add(panel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItem = new javax.swing.JMenu();
        MenuItemAdmin = new javax.swing.JMenuItem();
        menuItemEmpleado = new javax.swing.JMenuItem();
        menuItemCliente = new javax.swing.JMenuItem();
        menuItemAyuda = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuSalir = new javax.swing.JMenu();

        setMinimumSize(new java.awt.Dimension(980, 650));
        setUndecorated(true);
        getContentPane().setLayout(null);

        lb_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/back4.PNG"))); // NOI18N
        getContentPane().add(lb_background);
        lb_background.setBounds(-10, -30, 900, 310);

        jMenuBar1.setBackground(new java.awt.Color(160, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jMenuBar1.setOpaque(true);

        menuItem.setForeground(new java.awt.Color(204, 204, 204));
        menuItem.setText("Menu     |");
        menuItem.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActionPerformed(evt);
            }
        });

        MenuItemAdmin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemAdmin.setBackground(new java.awt.Color(204, 204, 204));
        MenuItemAdmin.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        MenuItemAdmin.setText("Administrador");
        MenuItemAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAdminActionPerformed(evt);
            }
        });
        menuItem.add(MenuItemAdmin);

        menuItemEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemEmpleado.setBackground(new java.awt.Color(204, 204, 204));
        menuItemEmpleado.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        menuItemEmpleado.setText("Empleado");
        menuItemEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmpleadoActionPerformed(evt);
            }
        });
        menuItem.add(menuItemEmpleado);

        menuItemCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemCliente.setBackground(new java.awt.Color(204, 204, 204));
        menuItemCliente.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        menuItemCliente.setText("Cliente");
        menuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClienteActionPerformed(evt);
            }
        });
        menuItem.add(menuItemCliente);

        menuItemAyuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemAyuda.setBackground(new java.awt.Color(204, 204, 204));
        menuItemAyuda.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        menuItemAyuda.setText("Manual de ayuda");
        menuItemAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAyudaActionPerformed(evt);
            }
        });
        menuItem.add(menuItemAyuda);

        jMenuBar1.add(menuItem);

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Cambio de usuario     |");
        jMenu1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        MenuSalir.setForeground(new java.awt.Color(255, 255, 255));
        MenuSalir.setText("Salir");
        MenuSalir.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        MenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSalirMouseClicked
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_MenuSalirMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        l.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_menuItemActionPerformed

    private void menuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClienteActionPerformed
        // TODO add your handling code here:
        newPanel(cliente);
        cliente.SetterAll();
    }//GEN-LAST:event_menuItemClienteActionPerformed

    private void menuItemEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmpleadoActionPerformed
        // TODO add your handling code here:
        newPanel(empleado);
        empleado.SetterAll();
    }//GEN-LAST:event_menuItemEmpleadoActionPerformed

    private void MenuItemAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAdminActionPerformed
        // TODO add your handling code here:
        newPanel(administrador);
        administrador.SetterAll();

    }//GEN-LAST:event_MenuItemAdminActionPerformed

    private void menuItemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAyudaActionPerformed
        // TODO add your handling code here:
        newPanel(ayuda);
    }//GEN-LAST:event_menuItemAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemAdmin;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lb_background;
    private javax.swing.JMenu menuItem;
    private javax.swing.JMenuItem menuItemAyuda;
    private javax.swing.JMenuItem menuItemCliente;
    private javax.swing.JMenuItem menuItemEmpleado;
    // End of variables declaration//GEN-END:variables
}
